/**
 * Seed manifests describe the FK-safe COPY load order for each app schema.
 *
 * Why a manifest:
 * - Keeps seeding JS-only (no `psql` execution for loading CSVs).
 * - Makes load order explicit and reviewable (FK-safe).
 * - Avoids parsing SQL `\copy` commands at runtime.
 *
 * Each entry relies on:
 * - `server/database/<app>/seedData/*.csv` existing
 * - the CSV header matching the column names to COPY into
 */

/** @type {Record<string, Array<{schema:string, table:string, file:string, nullEmpty:boolean}>>} */
export const seedManifests = {
  social: [
    { schema: "social_schema", table: "users", file: "./seedData/users.csv", nullEmpty: false },
    { schema: "social_schema", table: "posts", file: "./seedData/posts.csv", nullEmpty: false },
    { schema: "social_schema", table: "comments", file: "./seedData/comments.csv", nullEmpty: false },
    { schema: "social_schema", table: "likes", file: "./seedData/likes.csv", nullEmpty: false },
    { schema: "social_schema", table: "follows", file: "./seedData/follows.csv", nullEmpty: false },
    { schema: "social_schema", table: "hashtags", file: "./seedData/hashtags.csv", nullEmpty: false },
    { schema: "social_schema", table: "post_hashtags", file: "./seedData/post_hashtags.csv", nullEmpty: false },
    { schema: "social_schema", table: "bookmarks", file: "./seedData/bookmarks.csv", nullEmpty: false },
    { schema: "social_schema", table: "notifications", file: "./seedData/notifications.csv", nullEmpty: false },
    { schema: "social_schema", table: "stories", file: "./seedData/stories.csv", nullEmpty: false },
    { schema: "social_schema", table: "story_views", file: "./seedData/story_views.csv", nullEmpty: false },
    { schema: "social_schema", table: "post_views", file: "./seedData/post_views.csv", nullEmpty: false },
    { schema: "social_schema", table: "post_shares", file: "./seedData/post_shares.csv", nullEmpty: false },
    { schema: "social_schema", table: "messages", file: "./seedData/messages.csv", nullEmpty: false },
    { schema: "social_schema", table: "groups", file: "./seedData/groups.csv", nullEmpty: false },
    { schema: "social_schema", table: "group_members", file: "./seedData/group_members.csv", nullEmpty: false },
    { schema: "social_schema", table: "group_posts", file: "./seedData/group_posts.csv", nullEmpty: false },
    { schema: "social_schema", table: "user_blocks", file: "./seedData/user_blocks.csv", nullEmpty: false },
    { schema: "social_schema", table: "user_devices", file: "./seedData/user_devices.csv", nullEmpty: false },
    { schema: "social_schema", table: "login_history", file: "./seedData/login_history.csv", nullEmpty: false },
    { schema: "social_schema", table: "reports", file: "./seedData/reports.csv", nullEmpty: false },
    { schema: "social_schema", table: "post_mentions", file: "./seedData/post_mentions.csv", nullEmpty: false },
    { schema: "social_schema", table: "comment_mentions", file: "./seedData/comment_mentions.csv", nullEmpty: false },
    { schema: "social_schema", table: "ad_campaigns", file: "./seedData/ad_campaigns.csv", nullEmpty: false },
    { schema: "social_schema", table: "promoted_posts", file: "./seedData/promoted_posts.csv", nullEmpty: false },
  ],

  ecommerce: [
    { schema: "ecommerce_schema", table: "customers", file: "./seedData/customers.csv", nullEmpty: false },
    { schema: "ecommerce_schema", table: "addresses", file: "./seedData/addresses.csv", nullEmpty: false },
    { schema: "ecommerce_schema", table: "categories", file: "./seedData/categories.csv", nullEmpty: false },
    { schema: "ecommerce_schema", table: "products", file: "./seedData/products.csv", nullEmpty: false },
    { schema: "ecommerce_schema", table: "orders", file: "./seedData/orders.csv", nullEmpty: false },
    { schema: "ecommerce_schema", table: "order_items", file: "./seedData/order_items.csv", nullEmpty: false },
    { schema: "ecommerce_schema", table: "payments", file: "./seedData/payments.csv", nullEmpty: false },
    { schema: "ecommerce_schema", table: "reviews", file: "./seedData/reviews.csv", nullEmpty: false },
  ],

  food: [
    { schema: "food_schema", table: "users", file: "./seedData/users.csv", nullEmpty: false },
    { schema: "food_schema", table: "user_addresses", file: "./seedData/user_addresses.csv", nullEmpty: false },
    { schema: "food_schema", table: "restaurants", file: "./seedData/restaurants.csv", nullEmpty: false },
    { schema: "food_schema", table: "restaurant_operating_hours", file: "./seedData/restaurant_operating_hours.csv", nullEmpty: false },
    { schema: "food_schema", table: "menu_items", file: "./seedData/menu_items.csv", nullEmpty: false },
    { schema: "food_schema", table: "menu_item_availability_logs", file: "./seedData/menu_item_availability_logs.csv", nullEmpty: false },
    { schema: "food_schema", table: "coupons", file: "./seedData/coupons.csv", nullEmpty: false },
    { schema: "food_schema", table: "orders", file: "./seedData/orders.csv", nullEmpty: false },
    { schema: "food_schema", table: "order_status_history", file: "./seedData/order_status_history.csv", nullEmpty: false },
    { schema: "food_schema", table: "order_items", file: "./seedData/order_items.csv", nullEmpty: false },
    { schema: "food_schema", table: "drivers", file: "./seedData/drivers.csv", nullEmpty: false },
    { schema: "food_schema", table: "driver_shifts", file: "./seedData/driver_shifts.csv", nullEmpty: false },
    { schema: "food_schema", table: "driver_assignments", file: "./seedData/driver_assignments.csv", nullEmpty: false },
    { schema: "food_schema", table: "payments", file: "./seedData/payments.csv", nullEmpty: false },
    { schema: "food_schema", table: "reviews", file: "./seedData/reviews.csv", nullEmpty: false },
    { schema: "food_schema", table: "support_tickets", file: "./seedData/support_tickets.csv", nullEmpty: false },
    { schema: "food_schema", table: "coupon_usage_logs", file: "./seedData/coupon_usage_logs.csv", nullEmpty: false },
  ],

  ride: [
    { schema: "ride_schema", table: "users", file: "./seedData/users.csv", nullEmpty: false },
    { schema: "ride_schema", table: "drivers", file: "./seedData/drivers.csv", nullEmpty: false },
    { schema: "ride_schema", table: "driver_documents", file: "./seedData/driver_documents.csv", nullEmpty: false },
    { schema: "ride_schema", table: "vehicles", file: "./seedData/vehicles.csv", nullEmpty: false },
    { schema: "ride_schema", table: "locations", file: "./seedData/locations.csv", nullEmpty: false },
    { schema: "ride_schema", table: "driver_shifts", file: "./seedData/driver_shifts.csv", nullEmpty: false },
    { schema: "ride_schema", table: "rider_saved_places", file: "./seedData/rider_saved_places.csv", nullEmpty: false },
    { schema: "ride_schema", table: "promos", file: "./seedData/promos.csv", nullEmpty: false },
    { schema: "ride_schema", table: "surge_pricing", file: "./seedData/surge_pricing.csv", nullEmpty: false },
    { schema: "ride_schema", table: "trips", file: "./seedData/trips.csv", nullEmpty: false },
    { schema: "ride_schema", table: "fare_components", file: "./seedData/fare_components.csv", nullEmpty: false },
    { schema: "ride_schema", table: "trip_events", file: "./seedData/trip_events.csv", nullEmpty: false },
    { schema: "ride_schema", table: "trip_status_history", file: "./seedData/trip_status_history.csv", nullEmpty: false },
    { schema: "ride_schema", table: "payments", file: "./seedData/payments.csv", nullEmpty: false },
    { schema: "ride_schema", table: "driver_payouts", file: "./seedData/driver_payouts.csv", nullEmpty: false },
    { schema: "ride_schema", table: "driver_location_logs", file: "./seedData/driver_location_logs.csv", nullEmpty: false },
    { schema: "ride_schema", table: "trip_driver_matches", file: "./seedData/trip_driver_matches.csv", nullEmpty: false },
    { schema: "ride_schema", table: "rider_app_events", file: "./seedData/rider_app_events.csv", nullEmpty: false },
    { schema: "ride_schema", table: "driver_incentives", file: "./seedData/driver_incentives.csv", nullEmpty: false },
    { schema: "ride_schema", table: "driver_sessions", file: "./seedData/driver_sessions.csv", nullEmpty: false },
    { schema: "ride_schema", table: "rider_subscriptions", file: "./seedData/rider_subscriptions.csv", nullEmpty: false },
    { schema: "ride_schema", table: "safety_incidents", file: "./seedData/safety_incidents.csv", nullEmpty: false },
    { schema: "ride_schema", table: "ratings", file: "./seedData/ratings.csv", nullEmpty: false },
    { schema: "ride_schema", table: "support_tickets", file: "./seedData/support_tickets.csv", nullEmpty: false },
  ],

  movies: [
    { schema: "movies_schema", table: "users", file: "./seedData/users.csv", nullEmpty: false },
    { schema: "movies_schema", table: "profiles", file: "./seedData/profiles.csv", nullEmpty: false },
    { schema: "movies_schema", table: "devices", file: "./seedData/devices.csv", nullEmpty: false },
    { schema: "movies_schema", table: "subscription_plans", file: "./seedData/subscription_plans.csv", nullEmpty: false },
    { schema: "movies_schema", table: "subscriptions", file: "./seedData/subscriptions.csv", nullEmpty: false },
    { schema: "movies_schema", table: "promotions", file: "./seedData/promotions.csv", nullEmpty: false },
    { schema: "movies_schema", table: "billing_invoices", file: "./seedData/billing_invoices.csv", nullEmpty: false },
    { schema: "movies_schema", table: "payments", file: "./seedData/payments.csv", nullEmpty: false },
    { schema: "movies_schema", table: "content_categories", file: "./seedData/content_categories.csv", nullEmpty: false },
    { schema: "movies_schema", table: "titles", file: "./seedData/titles.csv", nullEmpty: false },
    { schema: "movies_schema", table: "title_categories", file: "./seedData/title_categories.csv", nullEmpty: false },
    { schema: "movies_schema", table: "title_localizations", file: "./seedData/title_localizations.csv", nullEmpty: false },
    { schema: "movies_schema", table: "people", file: "./seedData/people.csv", nullEmpty: false },
    { schema: "movies_schema", table: "title_credits", file: "./seedData/title_credits.csv", nullEmpty: false },
    { schema: "movies_schema", table: "seasons", file: "./seedData/seasons.csv", nullEmpty: false },
    { schema: "movies_schema", table: "episodes", file: "./seedData/episodes.csv", nullEmpty: false },
    { schema: "movies_schema", table: "audio_languages", file: "./seedData/audio_languages.csv", nullEmpty: false },
    { schema: "movies_schema", table: "title_audio_tracks", file: "./seedData/title_audio_tracks.csv", nullEmpty: false },
    { schema: "movies_schema", table: "subtitle_languages", file: "./seedData/subtitle_languages.csv", nullEmpty: false },
    { schema: "movies_schema", table: "title_subtitles", file: "./seedData/title_subtitles.csv", nullEmpty: false },
    { schema: "movies_schema", table: "content_licenses", file: "./seedData/content_licenses.csv", nullEmpty: false },
    { schema: "movies_schema", table: "content_availability", file: "./seedData/content_availability.csv", nullEmpty: false },
    { schema: "movies_schema", table: "watchlists", file: "./seedData/watchlists.csv", nullEmpty: false },
    { schema: "movies_schema", table: "continue_watching", file: "./seedData/continue_watching.csv", nullEmpty: false },
    { schema: "movies_schema", table: "viewing_sessions", file: "./seedData/viewing_sessions.csv", nullEmpty: false },
    { schema: "movies_schema", table: "playback_events", file: "./seedData/playback_events.csv", nullEmpty: false },
    { schema: "movies_schema", table: "downloads", file: "./seedData/downloads.csv", nullEmpty: false },
    { schema: "movies_schema", table: "ratings", file: "./seedData/ratings.csv", nullEmpty: false },
    { schema: "movies_schema", table: "app_events", file: "./seedData/app_events.csv", nullEmpty: false },
    { schema: "movies_schema", table: "search_queries", file: "./seedData/search_queries.csv", nullEmpty: false },
    { schema: "movies_schema", table: "recommendation_rows", file: "./seedData/recommendation_rows.csv", nullEmpty: false },
    { schema: "movies_schema", table: "experiments", file: "./seedData/experiments.csv", nullEmpty: false },
    { schema: "movies_schema", table: "experiment_variants", file: "./seedData/experiment_variants.csv", nullEmpty: false },
    { schema: "movies_schema", table: "experiment_assignments", file: "./seedData/experiment_assignments.csv", nullEmpty: false },
    { schema: "movies_schema", table: "recommendation_impressions", file: "./seedData/recommendation_impressions.csv", nullEmpty: false },
    { schema: "movies_schema", table: "recommendation_clicks", file: "./seedData/recommendation_clicks.csv", nullEmpty: false },
    { schema: "movies_schema", table: "notification_campaigns", file: "./seedData/notification_campaigns.csv", nullEmpty: false },
    { schema: "movies_schema", table: "notification_deliveries", file: "./seedData/notification_deliveries.csv", nullEmpty: false },
    { schema: "movies_schema", table: "support_tickets", file: "./seedData/support_tickets.csv", nullEmpty: false },
  ],

  bank: [
    { schema: "bank_schema", table: "users", file: "./seedData/users.csv", nullEmpty: false },
    { schema: "bank_schema", table: "user_addresses", file: "./seedData/user_addresses.csv", nullEmpty: false },
    { schema: "bank_schema", table: "branches", file: "./seedData/branches.csv", nullEmpty: false },
    { schema: "bank_schema", table: "employees", file: "./seedData/employees.csv", nullEmpty: false },
    { schema: "bank_schema", table: "kyc_records", file: "./seedData/kyc_records.csv", nullEmpty: false },
    { schema: "bank_schema", table: "beneficiaries", file: "./seedData/beneficiaries.csv", nullEmpty: false },
    { schema: "bank_schema", table: "account_products", file: "./seedData/account_products.csv", nullEmpty: false },
    { schema: "bank_schema", table: "accounts", file: "./seedData/accounts.csv", nullEmpty: false },
    { schema: "bank_schema", table: "account_holders", file: "./seedData/account_holders.csv", nullEmpty: false },
    { schema: "bank_schema", table: "account_limits", file: "./seedData/account_limits.csv", nullEmpty: false },
    { schema: "bank_schema", table: "transaction_categories", file: "./seedData/transaction_categories.csv", nullEmpty: false },
    { schema: "bank_schema", table: "merchants", file: "./seedData/merchants.csv", nullEmpty: false },
    { schema: "bank_schema", table: "transactions", file: "./seedData/transactions.csv", nullEmpty: false },
    { schema: "bank_schema", table: "transfers", file: "./seedData/transfers.csv", nullEmpty: false },
    { schema: "bank_schema", table: "cards", file: "./seedData/cards.csv", nullEmpty: false },
    { schema: "bank_schema", table: "card_transactions", file: "./seedData/card_transactions.csv", nullEmpty: false },
    { schema: "bank_schema", table: "atm_machines", file: "./seedData/atm_machines.csv", nullEmpty: false },
    { schema: "bank_schema", table: "atm_transactions", file: "./seedData/atm_transactions.csv", nullEmpty: false },
    { schema: "bank_schema", table: "billers", file: "./seedData/billers.csv", nullEmpty: false },
    { schema: "bank_schema", table: "bill_payments", file: "./seedData/bill_payments.csv", nullEmpty: false },
    { schema: "bank_schema", table: "loan_products", file: "./seedData/loan_products.csv", nullEmpty: false },
    { schema: "bank_schema", table: "loan_applications", file: "./seedData/loan_applications.csv", nullEmpty: false },
    { schema: "bank_schema", table: "loans", file: "./seedData/loans.csv", nullEmpty: false },
    { schema: "bank_schema", table: "loan_repayments", file: "./seedData/loan_repayments.csv", nullEmpty: false },
    { schema: "bank_schema", table: "fixed_deposits", file: "./seedData/fixed_deposits.csv", nullEmpty: false },
    { schema: "bank_schema", table: "recurring_deposits", file: "./seedData/recurring_deposits.csv", nullEmpty: false },
    { schema: "bank_schema", table: "reward_programs", file: "./seedData/reward_programs.csv", nullEmpty: false },
    { schema: "bank_schema", table: "reward_earnings", file: "./seedData/reward_earnings.csv", nullEmpty: false },
    { schema: "bank_schema", table: "reward_redemptions", file: "./seedData/reward_redemptions.csv", nullEmpty: false },
    { schema: "bank_schema", table: "complaints", file: "./seedData/complaints.csv", nullEmpty: false },
    { schema: "bank_schema", table: "fraud_alerts", file: "./seedData/fraud_alerts.csv", nullEmpty: false },
    { schema: "bank_schema", table: "support_tickets", file: "./seedData/support_tickets.csv", nullEmpty: false },
    { schema: "bank_schema", table: "notification_campaigns", file: "./seedData/notification_campaigns.csv", nullEmpty: false },
    { schema: "bank_schema", table: "notification_deliveries", file: "./seedData/notification_deliveries.csv", nullEmpty: false },
    { schema: "bank_schema", table: "audit_logs", file: "./seedData/audit_logs.csv", nullEmpty: false },
    { schema: "bank_schema", table: "app_events", file: "./seedData/app_events.csv", nullEmpty: false },
  ],

  realestate: [
    { schema: "realestate_schema", table: "users", file: "./seedData/users.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "owner_profiles", file: "./seedData/owner_profiles.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "seeker_profiles", file: "./seedData/seeker_profiles.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "executive_profiles", file: "./seedData/executive_profiles.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "user_documents", file: "./seedData/user_documents.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "owner_verification_requests", file: "./seedData/owner_verification_requests.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "locations", file: "./seedData/locations.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "properties", file: "./seedData/properties.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "property_ownership_history", file: "./seedData/property_ownership_history.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "amenities", file: "./seedData/amenities.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "property_amenities", file: "./seedData/property_amenities.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "listings", file: "./seedData/listings.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "listing_media", file: "./seedData/listing_media.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "listing_status_history", file: "./seedData/listing_status_history.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "listing_price_history", file: "./seedData/listing_price_history.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "shortlists", file: "./seedData/shortlists.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "property_views", file: "./seedData/property_views.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "inquiries", file: "./seedData/inquiries.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "property_visits", file: "./seedData/property_visits.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "offers", file: "./seedData/offers.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "rental_applications", file: "./seedData/rental_applications.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "leases", file: "./seedData/leases.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "rent_payments", file: "./seedData/rent_payments.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "maintenance_tickets", file: "./seedData/maintenance_tickets.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "referrals", file: "./seedData/referrals.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "support_tickets", file: "./seedData/support_tickets.csv", nullEmpty: false },
    { schema: "realestate_schema", table: "app_events", file: "./seedData/app_events.csv", nullEmpty: false },
  ],

  hospital: [
    { schema: "hospital_schema", table: "departments", file: "./seedData/departments.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "specializations", file: "./seedData/specializations.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "doctors", file: "./seedData/doctors.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "doctor_specializations", file: "./seedData/doctor_specializations.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "doctor_schedules", file: "./seedData/doctor_schedules.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "doctor_leaves", file: "./seedData/doctor_leaves.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "patients", file: "./seedData/patients.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "patient_addresses", file: "./seedData/patient_addresses.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "patient_allergies", file: "./seedData/patient_allergies.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "patient_conditions", file: "./seedData/patient_conditions.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "insurance_providers", file: "./seedData/insurance_providers.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "insurance_policies", file: "./seedData/insurance_policies.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "rooms", file: "./seedData/rooms.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "beds", file: "./seedData/beds.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "staff_users", file: "./seedData/staff_users.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "appointments", file: "./seedData/appointments.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "appointment_status_history", file: "./seedData/appointment_status_history.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "admissions", file: "./seedData/admissions.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "encounters", file: "./seedData/encounters.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "bed_allocations", file: "./seedData/bed_allocations.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "vital_signs", file: "./seedData/vital_signs.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "diagnoses", file: "./seedData/diagnoses.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "medications", file: "./seedData/medications.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "prescriptions", file: "./seedData/prescriptions.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "prescription_items", file: "./seedData/prescription_items.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "lab_test_catalog", file: "./seedData/lab_test_catalog.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "lab_orders", file: "./seedData/lab_orders.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "lab_order_items", file: "./seedData/lab_order_items.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "lab_results", file: "./seedData/lab_results.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "procedures", file: "./seedData/procedures.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "procedure_orders", file: "./seedData/procedure_orders.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "invoices", file: "./seedData/invoices.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "invoice_items", file: "./seedData/invoice_items.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "payments", file: "./seedData/payments.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "insurance_claims", file: "./seedData/insurance_claims.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "patient_feedback", file: "./seedData/patient_feedback.csv", nullEmpty: false },
    { schema: "hospital_schema", table: "audit_logs", file: "./seedData/audit_logs.csv", nullEmpty: false },
  ],

  education: [
    { schema: "education_schema", table: "institutions", file: "./seedData/institutions.csv", nullEmpty: false },
    { schema: "education_schema", table: "campuses", file: "./seedData/campuses.csv", nullEmpty: false },
    { schema: "education_schema", table: "academic_terms", file: "./seedData/academic_terms.csv", nullEmpty: false },
    { schema: "education_schema", table: "departments", file: "./seedData/departments.csv", nullEmpty: false },
    { schema: "education_schema", table: "programs", file: "./seedData/programs.csv", nullEmpty: false },
    { schema: "education_schema", table: "subjects", file: "./seedData/subjects.csv", nullEmpty: false },
    { schema: "education_schema", table: "courses", file: "./seedData/courses.csv", nullEmpty: false },
    { schema: "education_schema", table: "course_prerequisites", file: "./seedData/course_prerequisites.csv", nullEmpty: false },
    { schema: "education_schema", table: "users", file: "./seedData/users.csv", nullEmpty: false },
    { schema: "education_schema", table: "student_profiles", file: "./seedData/student_profiles.csv", nullEmpty: false },
    { schema: "education_schema", table: "guardian_relationships", file: "./seedData/guardian_relationships.csv", nullEmpty: false },
    { schema: "education_schema", table: "teacher_profiles", file: "./seedData/teacher_profiles.csv", nullEmpty: false },
    { schema: "education_schema", table: "classrooms", file: "./seedData/classrooms.csv", nullEmpty: false },
    { schema: "education_schema", table: "course_offerings", file: "./seedData/course_offerings.csv", nullEmpty: false },
    { schema: "education_schema", table: "course_teachers", file: "./seedData/course_teachers.csv", nullEmpty: false },
    { schema: "education_schema", table: "timetable_slots", file: "./seedData/timetable_slots.csv", nullEmpty: false },
    { schema: "education_schema", table: "enrollments", file: "./seedData/enrollments.csv", nullEmpty: false },
    { schema: "education_schema", table: "attendance_sessions", file: "./seedData/attendance_sessions.csv", nullEmpty: false },
    { schema: "education_schema", table: "attendance_records", file: "./seedData/attendance_records.csv", nullEmpty: false },
    { schema: "education_schema", table: "assignments", file: "./seedData/assignments.csv", nullEmpty: false },
    { schema: "education_schema", table: "assignment_submissions", file: "./seedData/assignment_submissions.csv", nullEmpty: false },
    { schema: "education_schema", table: "exams", file: "./seedData/exams.csv", nullEmpty: false },
    { schema: "education_schema", table: "exam_results", file: "./seedData/exam_results.csv", nullEmpty: false },
    { schema: "education_schema", table: "learning_materials", file: "./seedData/learning_materials.csv", nullEmpty: false },
    { schema: "education_schema", table: "material_views", file: "./seedData/material_views.csv", nullEmpty: false },
    { schema: "education_schema", table: "discussion_threads", file: "./seedData/discussion_threads.csv", nullEmpty: false },
    { schema: "education_schema", table: "discussion_posts", file: "./seedData/discussion_posts.csv", nullEmpty: false },
    { schema: "education_schema", table: "student_feedback", file: "./seedData/student_feedback.csv", nullEmpty: false },
    { schema: "education_schema", table: "fee_plans", file: "./seedData/fee_plans.csv", nullEmpty: false },
    { schema: "education_schema", table: "scholarships", file: "./seedData/scholarships.csv", nullEmpty: false },
    { schema: "education_schema", table: "student_fee_assignments", file: "./seedData/student_fee_assignments.csv", nullEmpty: false },
    { schema: "education_schema", table: "fee_invoices", file: "./seedData/fee_invoices.csv", nullEmpty: false },
    { schema: "education_schema", table: "payments", file: "./seedData/payments.csv", nullEmpty: false },
    { schema: "education_schema", table: "app_events", file: "./seedData/app_events.csv", nullEmpty: false },
    { schema: "education_schema", table: "support_tickets", file: "./seedData/support_tickets.csv", nullEmpty: false },
  ],

  chat: [
    { schema: "chat_schema", table: "users", file: "./seedData/users.csv", nullEmpty: false },
    { schema: "chat_schema", table: "workspaces", file: "./seedData/workspaces.csv", nullEmpty: false },
    { schema: "chat_schema", table: "user_devices", file: "./seedData/user_devices.csv", nullEmpty: false },
    { schema: "chat_schema", table: "workspace_members", file: "./seedData/workspace_members.csv", nullEmpty: false },
    { schema: "chat_schema", table: "roles", file: "./seedData/roles.csv", nullEmpty: false },
    { schema: "chat_schema", table: "role_permissions", file: "./seedData/role_permissions.csv", nullEmpty: false },
    { schema: "chat_schema", table: "member_roles", file: "./seedData/member_roles.csv", nullEmpty: false },
    { schema: "chat_schema", table: "channels", file: "./seedData/channels.csv", nullEmpty: false },
    { schema: "chat_schema", table: "channel_members", file: "./seedData/channel_members.csv", nullEmpty: false },
    { schema: "chat_schema", table: "conversations", file: "./seedData/conversations.csv", nullEmpty: false },
    { schema: "chat_schema", table: "conversation_members", file: "./seedData/conversation_members.csv", nullEmpty: false },
    { schema: "chat_schema", table: "messages", file: "./seedData/messages.csv", nullEmpty: false },
    { schema: "chat_schema", table: "message_attachments", file: "./seedData/message_attachments.csv", nullEmpty: false },
    { schema: "chat_schema", table: "message_reactions", file: "./seedData/message_reactions.csv", nullEmpty: false },
    { schema: "chat_schema", table: "message_mentions", file: "./seedData/message_mentions.csv", nullEmpty: false },
    { schema: "chat_schema", table: "message_reads", file: "./seedData/message_reads.csv", nullEmpty: false },
    { schema: "chat_schema", table: "message_pins", file: "./seedData/message_pins.csv", nullEmpty: false },
    { schema: "chat_schema", table: "saved_messages", file: "./seedData/saved_messages.csv", nullEmpty: false },
    { schema: "chat_schema", table: "user_presence_logs", file: "./seedData/user_presence_logs.csv", nullEmpty: false },
    { schema: "chat_schema", table: "calls", file: "./seedData/calls.csv", nullEmpty: false },
    { schema: "chat_schema", table: "call_participants", file: "./seedData/call_participants.csv", nullEmpty: false },
    { schema: "chat_schema", table: "invites", file: "./seedData/invites.csv", nullEmpty: false },
    { schema: "chat_schema", table: "notification_preferences", file: "./seedData/notification_preferences.csv", nullEmpty: false },
    { schema: "chat_schema", table: "notifications", file: "./seedData/notifications.csv", nullEmpty: false },
    { schema: "chat_schema", table: "moderation_actions", file: "./seedData/moderation_actions.csv", nullEmpty: false },
    { schema: "chat_schema", table: "app_events", file: "./seedData/app_events.csv", nullEmpty: false },
  ],
};

/**
 * Fetch a manifest for an app. Throws for unknown apps (fail fast).
 *
 * @param {string} appName
 * @returns {Array<{schema:string, table:string, file:string, nullEmpty:boolean}>}
 */
export function getSeedManifest(appName) {
  const m = seedManifests[String(appName || "").trim()];
  if (!m) throw new Error(`No seed manifest configured for app '${appName}'`);
  return m;
}

